const transactionSchema = {
  type: "object",
  properties: {
    amount: { type: "number", minimum: 1 },
    currency: { type: "string" },
    lang: { type: "string" },
    hookUrl: { type: "string" },
    callback: { type: "string" },
    callbackFail: { type: "string" },
    billing: {
      type: "object",
      properties: {
        firstName: { type: "string" },
        lastName: { type: "string" },
        address1: { type: "string" },
        city: { type: "string" },
        state: { type: "string" },
        country: { type: "string" },
        postalCode: { type: "string" },
        phone: { type: "string" },
        email: { type: "string" },
        externalUserId: { type: "string" },
        dateOfBirth: { type: "string" },
      },
      required: ["firstName"],
    },
    orderId: { type: "string" },
    cardToken: { type: "string" },
    payment3dsType: { type: "string" },
    kycVerified: { type: "boolean" },
    previousPaymentCount: { type: "integer", minimum: 0 },
    cardData: {
      type: "object",
      properties: {
        cardNumber: { type: "string" },
        cardHolderName: { type: "string" },
        cardExpiryDate: { type: "string" },
        cardExpiryDate2: { type: "string" },
        cardCvv: { type: "string" },
        browser: {
          type: "object",
          properties: {
            colorDepth: { type: "integer" },
            userAgent: { type: "string" },
            language: { type: "string" },
            timeZone: { type: "string" },
            screenWidth: { type: "integer" },
            javaEnabled: { type: "boolean" },
            customerIp: { type: "string" },
            screenHeight: { type: "integer" },
            windowHeight: { type: "integer" },
            timeZoneOffset: { type: "integer" },
            windowWidth: { type: "integer" },
          },
        },
      },
    },
    saveCard: { type: "boolean" },
    merchantInformation: {
      type: "object",
      properties: {
        name: { type: "string" },
        merchantName: { type: "string" },
        country: { type: "string" },
        address1: { type: "string" },
        administrativeArea: { type: "string" },
        locality: { type: "string" },
        postalCode: { type: "string" },
        url: { type: "string" },
        customerServicePhoneNumber: { type: "string" },
        categoryCode: { type: "string" },
        noteToBuyer: { type: "string" },
      },
    },
  },
  required: [
    "amount",
    "currency",
    "hookUrl",
    "callback",
    "callbackFail",
    "billing",
    "cardData",
  ],
}

module.exports = { transactionSchema }
